### ISSUE TITLE
Generator to install an configuration file in YAML to a rails project

### ISSUE THREAD

**Issue by satoryu** [satoryu/rakuten_web_service-rails#1]
## Usage

After adding `rakuten_web_service-rails` to the Gemfile in a target rails project, the following will be available: 

```
$ rails g rakuten_web_service:install
```

This command generates `config/rakuten_web_service.yml`:  to define configurations required to access Rakuten Web Service APIs.

The configuration file consists of the configurations for each environment: 

``` yaml
development:
  application_id: 

test:
  application_id: this-is-dummy-appllication-id

production:
  application_id: <%= ENV['RWS_APPLICATION_ID'] %>
  affiliate_id: <%= ENV['RWS_AFFILIATE_ID'] %>
```

`application_id` is required and `affiliate_id` is optional.
